on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: ESLint
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  evaluator_job:
    name: Evaluator step
    runs-on: ubuntu-18.04
    needs: eslint
    steps:
      - uses: actions/checkout@v2
      - name: Evaluator step
        id: evaluator
        uses: betrybe/cypress-evaluator-action@v5
        with:
          repository-test-name: 'betrybe/sd-0x-project-shopping-cart-tests'
          repository-test-branch: 'master'
        env:
          GITHUB_USER_TEST: ${{ github.actor }} 
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
